### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [4]:
import numpy as np
import random

In [9]:
vector = np.random.rand(10) #варіант з допомогою numpy
print(vector)

[0.51855394 0.62797241 0.96145854 0.52647375 0.14434786 0.0562153
 0.80403071 0.5822599  0.22327914 0.63818474]


In [10]:
vector_1 = [random.uniform(0, 1) for _ in range(10)] #з допомогою модуля random
print(vector_2)

[0.6276697740485749, 0.7328719270368156, 0.12917990218972386, 0.5913804631566992, 0.7990957969417689, 0.8069149044649708, 0.6722049696019241, 0.2269949703847851, 0.9826451920806627, 0.740073295009138]


In [12]:
matrix = np.array([[11, 14, 17],
                  [20, 23, 26],
                  [29, 32, 35]  ])
print(matrix)

[[11 14 17]
 [20 23 26]
 [29 32 35]]



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [17]:
vector_2 = np.round(vector + 10, 2) #додав до кожного значення 10 та округлив до 2 знаків
print(vector_2)

[10.52 10.63 10.96 10.53 10.14 10.06 10.8  10.58 10.22 10.64]


In [18]:
matrix_2 = matrix * 2 #помножив кожен елемент матриці на 2
print(matrix_2)

[[22 28 34]
 [40 46 52]
 [58 64 70]]


In [19]:
vector_3 = vector ** 2 #створив новий вектор, який містить квадрат кожного vector без циклів 
print(vector_3)

[0.26889818 0.39434935 0.92440253 0.27717461 0.02083631 0.00316016
 0.64646538 0.33902659 0.04985358 0.40727976]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [16]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [31]:
result_matrix = np.dot(B, A) #підзавдання 1. Щоб вийшов розмір 2 на 2, то нам треба В помножити на А, а не навпаки.
print(sum_matrix)

[[0.7281 0.5202]
 [0.2034 0.2846]]


In [ ]:
Очікую, що розмір буде (2,1), бо це ми фактично множимо 

In [32]:
res_mult_C = np.dot(sum_matrix, C) #підзавдання 2
print(sum_mult_C)

[[0.5202]
 [0.2846]]


In [33]:
res_mult_C.shape #очікування підтвердилися, ще для ілюстрації розміру

(2, 1)

In [36]:
res_mult_D = np.dot(result_matrix, D) #Підзавдання 3, як й очікувалося, розмір (2, 2)
print(res_mult_D)

[[0.5202 0.7281]
 [0.2846 0.2034]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [40]:
result_matrix_transposed = result_matrix.T #підзавдання 1 - транспонування матриці
print(result_matrix_transposed)

[[0.7281 0.2034]
 [0.5202 0.2846]]


In [47]:
vector_transposed = vector.T #підзавдання 2 - транспонування вектора
print(vector_transposed)

[0.51855394 0.62797241 0.96145854 0.52647375 0.14434786 0.0562153
 0.80403071 0.5822599  0.22327914 0.63818474]


**Спостереження** Зміни не бачу. Мабуть транспонування вектора не змінює його розмір.

In [49]:
column_vector = np.expand_dims(vector, axis=1) #підзавдання 3 - перетворення вектора в стовпець
print(column_vector)

[[0.51855394]
 [0.62797241]
 [0.96145854]
 [0.52647375]
 [0.14434786]
 [0.0562153 ]
 [0.80403071]
 [0.5822599 ]
 [0.22327914]
 [0.63818474]]


In [54]:
column_vector.shape

(10, 1)

Ми бачимо, що тепер цей вектор відображається у вигляді стовпця, бо ми його перетворили у стовпець.

In [52]:
column_vector_transposed = column_vector.T #підзавдання транспонування вектора
print(column_vector_transposed)

[[0.51855394 0.62797241 0.96145854 0.52647375 0.14434786 0.0562153
  0.80403071 0.5822599  0.22327914 0.63818474]]


In [53]:
column_vector_transposed.shape

(1, 10)